//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fatura
    {
        public int Id { get; set; }
        public Nullable<int> IdPaciente { get; set; }
        public Nullable<int> IdTratamento { get; set; }
        public Nullable<int> IdExame { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> DataFatura { get; set; }
        public Nullable<int> IdInternamento { get; set; }
    
        public virtual Exame Exame { get; set; }
        public virtual Internamento Internamento { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual Tratamento Tratamento { get; set; }
    }
}
